# 问题二配置 - 有风条件下的林火蔓延
# 基于激进配置，启用风效应模块

# 继承激进配置的基础参数
base_spread_rate: 3.0           # 基础蔓延速度 (m/min)
fuel_coefficient: 4.0           # 可燃物系数
moisture_factor_b: 3.0          # 湿度阻抗因子

# 坡度效应参数
slope_factor_a: 0.5             # 坡度因子
max_slope_deg: 55.0

# 风效应参数 - 问题二关键
wind_speed_factor_c: 0.6        # 风速因子 0.4→0.6（增强风效应）
wind_speed_power_d: 1.3         # 风速指数 1.5→1.3（平滑风速影响）
wind_direction_factor_k: 4.0    # 风向因子 3.0→4.0（增强方向性）

# 多种风况配置
wind_scenarios:
  # 情景1：3m/s东风
  scenario_1:
    wind_speed: 3.0             # m/s
    wind_direction_deg: 90.0    # 正东方向
    description: "3m/s东风"
    
  # 情景2：5m/s东北风  
  scenario_2:
    wind_speed: 5.0             # m/s
    wind_direction_deg: 45.0    # 东北方向
    description: "5m/s东北风"
    
  # 情景3：8m/s南风（强风）
  scenario_3:
    wind_speed: 8.0             # m/s
    wind_direction_deg: 180.0   # 正南方向
    description: "8m/s南风"

# 默认风况（使用情景1）
default_wind_scenario: "scenario_1"

# 湿度和温度参数
evaporation_coefficient: 0.01

# 燃料参数
initial_fuel_load: 3.0
initial_moisture_content: 0.08
fuel_consumption_rate: 0.03

# 点燃参数
base_ignition_energy: 50.0
ignition_moisture_factor: 1.0

# 能量传递优化
energy_transfer_multiplier: 20.0
min_energy_transfer: 2.0

# 树冠火参数（问题二保持关闭）
crown_fire_multiplier: 3.0
critical_fire_intensity: 500.0

# 飞火参数（有风条件下可能启用）
spotting_probability: 0.02      # 小概率飞火 0.0→0.02

# 模拟参数
max_simulation_time: 4320       # 72小时
time_step: 1.0
cell_size: 10.0

# 问题二的开关设置
enable_wind_effects: true       # 启用风效应！
enable_crown_fire: false       # 仍关闭树冠火
enable_spotting: true          # 启用少量飞火
enable_dynamic_moisture: true

# 起火点配置（与问题一相同）
ignition_points:
  point_A:
    position: [1500.0, 1500.0]
    radius: 15.0
  point_B:
    position: [1500.0, 2000.0]
    radius: 15.0

# 输出时间点
output_times: [24, 48, 72]

# 地形参数
terrain:
  width: 300
  height: 300
  slope_angle_deg: 30.0
  intersection_distance: 1500.0 